name: File checker

on:
  pull_request:

jobs:
  build:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Check for Changed Files
      uses: brettcannon/check-for-changed-files@v1.0.0
      with:
        file-pattern: |
          README.md