name: My Workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # Checkout is required before did-files-change
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # be sure to override the default value (1) for fetch-depth

      - name: Check changes
        id: check-changes
        uses: rdietrick/did-files-change@v1.2
        with:
          pathspec: README.md

      - name: Debug
        run: |
          number=${{ steps.check-changes.outputs.changed }}
          if [ $number -gt 0 ]
          then
          echo "Changes detected in README.md : ${{ steps.check-changes.outputs.changed }}"
          else
          echo "No changes detected in README.md. Exiting"
          exit 1

