name: My Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Read Helm Chart
      id: chart
      uses: jacobtomlinson/gha-read-helm-chart@master
      with:
        path: ./_helm/sdx-seft/Chart.yaml
    - name: Print outputs
        run: echo "App Version - ${{ steps.chart.outputs.appVersion }}"
