name: Checking version number
on:
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Read Helm Chart
      id: chart
      uses: jacobtomlinson/gha-read-helm-chart@master
      with:
        path: path/to/chart
    - name: Print outputs
        run: |
        echo "Name - ${{ steps.chart.outputs.name }}"
        echo "Version - ${{ steps.chart.outputs.version }}"
        echo "App Version - ${{ steps.chart.outputs.appVersion }}"
