name: Build

on: [push]

jobs:
  build:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: make build
      run: |
        export PYTHONPATH=.
        make build
        pip install codecov
    - name: run tests
      run: |
        make test
    - name: get coverage
      run: |
        codecov


