name: Build

on:
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: run tests
      run: |
        pip install -r test_requirements.txt
        pytest --cache-clear --cov=app tests/ > pytest-coverage.txt
    - name: Comment coverage
      uses: coroo/pytest-coverage-commentator@v1.0.2
    - name: pytest-coverage-commentator
      uses: coroo/pytest-coverage-commentator@v1.0.2
      with:
        pytest-coverage: pytest-coverage.txt

    - name: Read Helm Chart
      id: chart
      uses: jacobtomlinson/gha-read-helm-chart@master
      with:
        path: ./_helm/sdx-seft
    - name: Print outputs
      run: echo ${{ steps.chart.outputs.appVersion }}

    - name: Getting main version
      uses: actions/checkout@v2
      with:
        ref: main
        fetch-depth: 1
    - name: Read Helm Chart
      id: chart-main
      uses: jacobtomlinson/gha-read-helm-chart@master
      with:
        path: ./_helm/sdx-seft
    - name: Print outputs
      run: echo ${{ steps.chart-main.outputs.appVersion }}
    - name: Compare appVersion
      run: |
        if [[ "${{ steps.chart-main.outputs.appVersion }}" != "${{ steps.chart.outputs.appVersion }}" ]]
        then
          echo Version updated!
        else:
          echo Version not updated!
          exit 1
        fi
